# Включить ли проактивные подсказки
enabled: false
# Минимальный интервал между подсказками в минутах
suggestion_min_interval_min: 60
# Отправлять ли подсказки только в Telegram
force_telegram: false
# Интервал "тихого" времени, когда подсказки не показываются
silence_window:
  start: "22:00"
  end: "08:00"
